version: "3.3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongo_from_compose
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=userAdmin
      - MONGO_INITDB_ROOT_PASSWORD=userPassword
