apiVersion: v1
kind: PersistentVolume
metadata:
  name: datascientest-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
  storageClassName: slow
