apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: httpd-replicaset
spec:
    replicas: 3
    selector:
       matchLabels:
          app: httpd
    template:
       metadata:
          labels:
            app: httpd
            env: dev
       spec:
          containers:
          - name: httpd
            image: httpd
